# Experiments Analysis Notebook

In [1]:
import pandas as pd
import numpy as np
import matplotlib

%matplotlib inline

import sys
import os 
import pathlib
##### set up root dir
# Get the current working directory
file_path = os.path.join(os.getcwd(), 'results_analysis.ipynb')
# rootdir = os.path.dirname(file_path)

directory = os.path.dirname(file_path)

directory = pathlib.Path(directory)

In [2]:
##### Summary stat functions and plotting########

def get_summary_stats(df:pd.DataFrame):
    summary_stats = df[["reward",
                        "steps",
                        "time",
                        "collisions",
                        "found_all_rewards",
                        "num_reward_blocks",
                        "num_obstacle_blocks"]].describe()

    return summary_stats


def get_mean_and_std_err(df:pd.DataFrame,varname:str):
    m = df[varname].mean()
    sderr = df[varname].std()/np.sqrt(df[varname].count())

    return m,sderr

In [3]:
######### Baseline MCTS #############
basline_mcts_5x5 = pd.read_csv(directory / "results/baseline_mcts_5x5.csv")
print("Mean {0}, StdErr {1}".format(*get_mean_and_std_err(basline_mcts_5x5,"reward")))
get_summary_stats(basline_mcts_5x5)

Mean 0.5720329067641681, StdErr 0.07186310167598083

,reward,steps,time,collisions,found_all_rewards,num_reward_blocks,num_obstacle_blocks
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.00000,150.000000
mean,0.572033,17.613333,26.656690,4.206667,0.986667,4.26000,5.506667
std,0.880140,18.788039,37.964682,8.310498,0.115082,2.94566,2.696621
min,-5.800000,1.000000,0.157218,0.000000,0.000000,1.00000,1.000000
25%,0.600000,7.000000,3.746364,0.000000,1.000000,2.00000,3.000000
50%,0.800000,12.000000,12.110295,2.000000,1.000000,3.00000,5.000000
75%,1.000000,21.000000,33.400216,4.000000,1.000000,7.00000,8.000000
max,1.000000,100.000000,194.269252,58.000000,1.000000,13.00000,14.000000

In [4]:
baseline_mcts_10x10 = pd.read_csv(directory/"results/baseline_mcts_10x10.csv")
print("Mean {0}, StdErr {1}".format(*get_mean_and_std_err(baseline_mcts_10x10,"reward")))
get_summary_stats(baseline_mcts_10x10)

Mean -0.14287333156759477, StdErr 0.059818776565357716

,reward,steps,time,collisions,found_all_rewards,num_reward_blocks,num_obstacle_blocks
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,-0.142873,81.933333,270.164928,4.846667,0.280000,6.400000,9.733333
std,0.732627,32.129283,126.649490,4.884899,0.450503,4.169239,5.391600
min,-2.207383,5.000000,4.343400,0.000000,0.000000,1.000000,2.000000
25%,-0.600000,73.250000,215.971548,1.000000,0.000000,3.000000,5.250000
50%,-0.161074,100.000000,300.611990,3.000000,0.000000,5.000000,9.000000
75%,0.475000,100.000000,372.376629,7.000000,1.000000,10.000000,13.000000
max,1.000000,100.000000,418.456275,26.000000,1.000000,16.000000,24.000000

In [5]:
baseline_mcts_20x20 = pd.read_csv(directory/"results/baseline_mcts_20x20.csv")
print("Mean {0}, StdErr {1}".format(*get_mean_and_std_err(baseline_mcts_20x20,"reward")))
get_summary_stats(baseline_mcts_20x20)

Mean -0.012479313569884222, StdErr 0.022845224157634843

,reward,steps,time,collisions,found_all_rewards,num_reward_blocks,num_obstacle_blocks
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,-0.012479,298.313333,1503.432357,2.026667,0.006667,39.913333,48.660000
std,0.279796,20.657363,288.469078,2.374209,0.081650,16.462663,32.175865
min,-0.969608,47.000000,253.453935,0.000000,0.000000,3.000000,5.000000
25%,-0.184684,300.000000,1342.422292,0.000000,0.000000,27.000000,19.250000
50%,0.043738,300.000000,1572.027534,1.000000,0.000000,37.500000,42.000000
75%,0.174844,300.000000,1730.374855,3.000000,0.000000,52.000000,70.750000
max,0.800000,300.000000,1913.830397,13.000000,1.000000,83.000000,132.000000